frr version 9.1
frr defaults traditional
hostname r2
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description to-h2 (10.10.2.0/24)
 ip address 10.10.2.1/24
 ip ospf area 0
!
interface eth2
 description to-r1 (transit 10.0.0.0/30)
 ip address 10.0.0.2/30
 ip ospf area 0
!
router ospf
 ospf router-id 2.2.2.2
!
line vty
!
