frr version 10.6
frr defaults traditional
hostname r1
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description to-h1 (10.10.1.0/24)
 ip address 10.10.1.1/24
 ip ospf area 0
!
interface eth2
 description to-r2 PRIMARY (transit 10.0.0.0/30)
 ip address 10.0.0.1/30
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf cost 10
 ip ospf hello-interval 2
 ip ospf dead-interval 8
!
interface eth3
 description to-r3 BACKUP (transit 10.0.1.0/30)
 ip address 10.0.1.1/30
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf cost 10
 ip ospf hello-interval 2
 ip ospf dead-interval 8
!
router ospf
 ospf router-id 1.1.1.1
 passive-interface eth1
!
line vty
!
